ARMGNU := arm-none-eabi
BUILD_DIR := build
OBJ_DIR := $(BUILD_DIR)/obj
BIN_DIR := $(BUILD_DIR)/bin
SRC := src

program_NAME := MegOS

# This is a list of all files in the current directory ending in ".c". The $(wildcard) is a globbing expression. This similar to how the shell expands *.c
program_C_SRCS := $(wildcard $(SRC)/*.c)

program_ASM_SRCS := $(wildcard $(SRC)/*.s)

program_SRCS := $(program_C_SRCS) $(program_ASM_SRCS)

# This is simply a list of all the ".o" files, both from C and C++ source files.
program_OBJS :=  $(patsubst $(SRC)/%.c, $(OBJ_DIR)/%.o, $(program_C_SRCS)) \
                 $(patsubst $(SRC)/%.s, $(OBJ_DIR)/%.o, $(program_ASM_SRCS))


all: $(BUILD_DIR) $(BIN_DIR) $(OBJ_DIR) $(program_NAME)

$(BUILD_DIR) $(BIN_DIR) $(OBJ_DIR):
	mkdir $(subst /,\\,$@)


$(program_NAME): $(program_OBJS)
	$(ARMGNU)-ld -nostartfiles -T linker.ld $(program_OBJS) -o $(BIN_DIR)/$(program_NAME).elf
	$(ARMGNU)-objcopy -O binary $(BIN_DIR)/$(program_NAME).elf $(BIN_DIR)/$(program_NAME)
	$(ARMGNU)-objdump -D $(BIN_DIR)/$(program_NAME).elf > $(BIN_DIR)/$(program_NAME).list
	btoi.exe $(BIN_DIR)/$(program_NAME) $(BIN_DIR)/$(program_NAME)_ti

$(OBJ_DIR)/%.o: $(SRC)/%.c
	$(ARMGNU)-gcc -c $< -o $@

$(OBJ_DIR)/%.o: $(SRC)/%.s
	$(ARMGNU)-as -c $< -o $@
	
clean:
	rmdir /s /q $(BUILD_DIR)