ARMGNU := arm-none-eabi
TEMPDIR := build
SRC := src

program_NAME := MegOS

# This is a list of all files in the current directory ending in ".c". The $(wildcard) is a globbing expression. This similar to how the shell expands *.c
program_C_SRCS := $(wildcard $(SRC)/*.c)

program_ASM_SRCS := $(wildcard $(SRC)/*.s)

program_SRCS := $(program_C_SRCS) $(program_ASM_SRCS)

# This is simply a list of all the ".o" files, both from C and C++ source files.
program_OBJS :=  $(patsubst $(SRC)/%.c, $(TEMPDIR)/%.o, $(program_C_SRCS)) \
                 $(patsubst $(SRC)/%.s, $(TEMPDIR)/%.o, $(program_ASM_SRCS))

all: $(program_NAME)

$(program_NAME): $(program_OBJS)
	$(ARMGNU)-ld -nostartfiles -T linker.ld $(program_OBJS) -o $(program_NAME).elf
	$(ARMGNU)-objcopy -O binary $(program_NAME).elf $(program_NAME)
	$(ARMGNU)-objdump -D $(program_NAME).elf > $(program_NAME).list
	btoi.exe $(program_NAME) $(program_NAME)_ti

$(TEMPDIR)/%.o: $(SRC)/%.c
	$(ARMGNU)-gcc -c $< -o $@

$(TEMPDIR)/%.o: $(SRC)/%.s
	$(ARMGNU)-as -c $< -o $@
	
clean:
	rm $(program_OBJS) $(program_NAME) $(program_NAME)_ti $(program_NAME).elf $(program_NAME).list